language: python

matrix:
  include:
   - python: 3.4
     dist: trusty
     sudo: false
   - python: 3.5
     dist: trusty
     sudo: false
   - python: 3.6
     dist: trusty
     sudo: false
   - python: 3.7
     dist: xenial
     sudo: true

env:
 - DJANGO=2.1.7

install:
 - pip install -r niffler/requirements.txt

script:
 - python niffler/manage.py test questionnaire

branches:
  only:
   - master