# Generated by Django 2.1.7 on 2019-06-24 15:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import questionnaire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('verification_code', models.CharField(default='123456', max_length=40)),
                ('code_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participantship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participanted_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('poll', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('_status', models.CharField(blank=True, choices=[('UNDERWAY', 'UNDERWAY'), ('CANCELLED', 'CANCELLED'), ('CONFIRMED', 'CONFIRMED')], default='UNDERWAY', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('balance', models.IntegerField(blank=True, default=10000)),
                ('avatar', models.ImageField(blank=True, upload_to=questionnaire.models.Profile.content_file_name)),
                ('birth', models.DateField(blank=True, null=True)),
                ('stuId', models.CharField(max_length=8, null=True)),
                ('grade', models.CharField(choices=[('大一', '大一'), ('大二', '大二'), ('大三', '大三'), ('大四', '大四')], default='大一', max_length=4)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('poll', models.TextField(blank=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('participant_quota', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('task_type', models.CharField(choices=[('问卷', '问卷'), ('跑腿', '跑腿')], default='questionnaire', max_length=4)),
                ('claimers', models.ManyToManyField(blank=True, related_name='claimed_tasks', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tasks', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participanted_tasks', through='questionnaire.Participantship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='questionnaire.Task'),
        ),
        migrations.AddField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantship',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Task'),
        ),
        migrations.AddField(
            model_name='participantship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
