# Generated by Django 2.2.1 on 2019-06-02 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participanted_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('poll', models.FileField(blank=True, upload_to='participanted_poll/%Y/%m/%d/')),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('self_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('poll', models.FileField(blank=True, upload_to='task_poll/%Y/%m/%d/')),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('participant_quota', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('self_cancelled', models.BooleanField(default=False)),
                ('claimers', models.ManyToManyField(related_name='claimed_tasks', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tasks', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participanted_tasks', through='questionnaire.Participantship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tasks', models.ManyToManyField(to='questionnaire.Task')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('balance', models.IntegerField(blank=True, default=10000)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participantship',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Task'),
        ),
        migrations.AddField(
            model_name='participantship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
