# Generated by Django 2.2.1 on 2019-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantship',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
