# Generated by Django 2.1.7 on 2019-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190625_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantship',
            name='poll',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
