# Generated by Django 2.2.1 on 2019-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_participantship_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantship',
            old_name='finished_date',
            new_name='confirmed_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='self_cancelled',
            new_name='cancelled',
        ),
        migrations.RemoveField(
            model_name='participantship',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='participantship',
            name='self_cancelled',
        ),
        migrations.AddField(
            model_name='participantship',
            name='_status',
            field=models.CharField(blank=True, choices=[('UNDERWAY', 'UNDERWAY'), ('CANCELLED', 'CANCELLED'), ('CONFIRMED', 'CONFIRMED')], default='UNDERWAY', max_length=100),
        ),
    ]
