# Generated by Django 2.1.7 on 2019-06-21 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20190621_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantship',
            name='poll',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
