# Generated by Django 2.2.1 on 2019-06-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20190621_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='poll',
            field=models.TextField(blank=True),
        ),
    ]
