# Generated by Django 2.1.7 on 2019-06-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20190621_1211'),
        ('questionnaire', '0008_auto_20190621_1224'),
    ]

    operations = [
    ]
