# Generated by Django 2.2.1 on 2019-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20190622_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
