# Generated by Django 2.2.1 on 2019-06-22 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20190622_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('问卷', '问卷'), ('跑腿', '跑腿')], default='问卷', max_length=4),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='questionnaire.Task'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='claimers',
            field=models.ManyToManyField(blank=True, related_name='claimed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participanted_tasks', through='questionnaire.Participantship', to=settings.AUTH_USER_MODEL),
        ),
    ]
