# Generated by Django 2.2.1 on 2019-06-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20190622_0307'),
        ('questionnaire', '0009_merge_20190622_0219'),
    ]

    operations = [
    ]
