# Generated by Django 2.1.7 on 2019-06-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_merge_20190622_0219'),
        ('questionnaire', '0011_auto_20190622_0307'),
    ]

    operations = [
    ]
