# Generated by Django 2.2.1 on 2019-06-22 11:36

from django.db import migrations, models
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_merge_20190622_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=questionnaire.models.Profile.content_file_name),
        ),
    ]
