# Generated by Django 2.1.7 on 2019-06-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_merge_20190622_0411'),
        ('questionnaire', '0013_auto_20190622_1136'),
    ]

    operations = [
    ]
