# Generated by Django 2.2.1 on 2019-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20190623_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('问卷', '问卷'), ('跑腿', '跑腿')], default='questionnaire', max_length=4),
        ),
    ]
