# Generated by Django 2.2.1 on 2019-06-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20190623_1657'),
        ('questionnaire', '0014_merge_20190623_1253'),
    ]

    operations = [
    ]
